name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov httpx
        working-directory: backend      # ← entra na pasta certa

      - name: Rodar testes
        run: PYTHONPATH=. pytest tests/ -v --cov=. --cov-fail-under=50
        working-directory: backend      # ← roda de dentro do backend

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend